# Generated by Django 4.2.13 on 2024-08-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('acronimo', models.CharField(default='', max_length=10)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=70)),
                ('old_name', models.CharField(max_length=70)),
                ('extension', models.CharField(max_length=10)),
                ('file_name', models.TextField()),
                ('code', models.CharField(max_length=10)),
                ('script', models.TextField()),
                ('acronimo', models.CharField(max_length=10, null=True)),
                ('num_images', models.IntegerField(default=0)),
                ('fecha', models.TextField(default='')),
                ('position', models.TextField(default='')),
            ],
        ),
    ]
